name: Pytket Qsharp Docs

on:
  push:
    branches:
      - 'docs/**'
  schedule:
    # 04:00 every Tuesday morning
    - cron: '0 4 * * 2'

jobs:
  docs:
    name: build docs
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Upgrade pip and install wheel
      run: pip install --upgrade pip wheel jupyterlab
    - name: Install pytket qsharp
      run: pip install .
    - name: Install dotnet SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
    - name: Install iqsharp
      run: |
        dotnet tool install -g Microsoft.Quantum.IQSharp
        dotnet iqsharp install --user
    - name: Install docs dependencies
      run: |
        pip install -r .github/workflows/docs/requirements.txt
    - name: Test building docs
      timeout-minutes: 20
      run: |
        cd .github/workflows/docs
        mkdir extensions
        ./build-docs -d ${GITHUB_WORKSPACE}/.github/workflows/docs/extensions
    - uses: actions/upload-artifact@v3
      with:
        name: pytket-extension-docs
        path: .github/workflows/docs/extensions/
